# example values
indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://www.playback.ru/
      name: PlayBack.Ru
    - url: https://ipfran.ru/
      name: Институт прикладной физики
    - url: https://dimonvideo.ru/
      name: Все для мобильных устройств
    - url: https://www.svetlovka.ru/
      name: Библиотека Светловка
    - url: https://www.atomstroy.net/
      name: Атом строй комплекс
    - url: https://nikoartgallery.com/
      name: Креативное пространство
    - url: https://radiomv.ru/
      name: Радио

server:
  port: 10100
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/search_engine_db
    url: jdbc:postgresql://localhost:5432/search_engine_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    #password: testPass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 60000
      pool-name: SearchEngineHikariPool
      connection-test-query: SELECT 1
      validation-timeout: 3000
      max-lifetime: 1800000 # 30 минут
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        default_schema: sites_parsing
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        flush_mode: COMMIT
        generate_statistics: false
        show_sql: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #searchengine: DEBUG

connect:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
  referrer: http://www.google.com

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true