# example values
indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://charutti.ru
      name: Бренд ЧАРУТТИ
    - url: https://opt-opt-opt.ru
      name: ТриОпт
    - url: https://dombulgakova.ru
      name: PДом Булгакова
    - url: https://www.svetlovka.ru
      name: Светловка

server:
  port: 10100
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/search_engine_db
    url: jdbc:postgresql://localhost:5432/search_engine_db
    username: se_user
    password: app$diplomU$er
    #password: testPass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 60000
      pool-name: SearchEngineHikariPool
      connection-test-query: SELECT 1
      validation-timeout: 3000
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        default_schema: sites_parsing
        format_sql: false
        use_sql_comments: true
        highlight_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        flush_mode: COMMIT
        generate_statistics: false
        show_sql: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO

connect:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
  referrer: http://www.google.com

file:
  extensions: pdf|PDF|docx?|DOCX?|xlsx?|XLSX?|jpg|pptx?|PPTX?|jpe?g|JPE?G|gif|GIF|png|PNG|mp3|MP3|mp4|MP4|aac|AAC|json|JSON|csv|CSV|exe|EXE|apk|APK|rar|RAR|zip|ZIP|xml|XML|jar|JAR|bin|BIN|svg|SVG|nc|NC|webp|WEBP|m|M|fig|FIG|eps|EPS

error:
  interrupted: Indexing stopped by user
  certificate: Site's certificate validity check failed
  unknown: Unknown error
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true